services:
  datapub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: datapub
    volumes:
      - ./src:/app/src
      - ./storage:/app/storage
    working_dir: /app
    command: bash
    depends_on:
      - postgres
      - neo4j
    env_file:
      - .env  
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
      DATABASE_URL: postgresql://cognee:cognee@postgres:5432/cognee_db
      NEO4J_URL: bolt://neo4j:7687

  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  neo4j:
    image: neo4j:5.19-community
    container_name: neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # BOLT
    environment:
      NEO4J_AUTH: neo4j/pleaseletmein
      NEO4J_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: 'apoc.*,gds.*'
      NEO4J_dbms_security_procedures_allowlist: 'apoc.*,gds.*'
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
    volumes:
      - neo4j_data:/data
      # - ./plugins:/plugins

volumes:
  pg_data:
  pgadmin_data:
  neo4j_data:
