services:
  postgres:
    image: postgres:15
    build: ./docker/postgres  
    environment:
      POSTGRES_PASSWORD: diarios
      POSTGRES_DB: diarios
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql 
    ports:
      - "5432:5432"
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
  
  api:
    build: ./src/api
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
    environment:
      DB_URL: postgresql://postgres:diarios@postgres/diarios
      ES_URL: http://elasticsearch:9200
  
  frontend:
    build: ./src/frontend
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pg_data:
  es_data:
